platform:ios, '8.0'

target 'YYDineTogether' do
use_frameworks!
pod 'MJRefresh'
pod 'AFNetworking', '~> 3.0'
pod 'YYKit'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry'
pod 'SDWebImage', '~>3.7.3'
pod 'AMap3DMap-NO-IDFA' #3D地图SDK(2D地图和3D地图不能同时使用)
pod 'AMapSearch-NO-IDFA' #搜索服务SDK
pod 'AMapLocation-NO-IDFA'
pod 'JPush', '~>3.0.2'
end
